### PR TITLE
Issue/30 prompt for passphrase if needed

### PR DESCRIPTION
**Pull request by spkane**
**closes:** https://github.com/superorbital/cludo/issues/30

This adds an interactive prompt for the SSH key passphrase when the system is having trouble decoding the key.

It also adds an interactive CLI switch which can be used to disable the prompting for scripts, etc.

### CODE REVIEW

**Comment by tammersaleh** [comment]
I feel like we're going to move to something different (maybe ssh-agent, maybe drop ssh key support) in the near future.  This PR is probably fine for now, just to quickly work around the "can't use a passphrase key" problem.

**Comment by spkane** [comment]
> I feel like we're going to move to something different (maybe ssh-agent, maybe drop ssh key support) in the near future. This PR is probably fine for now, just to quickly work around the "can't use a passphrase key" problem.

Yep. I assumed we'd add ssh-agent support on top of this, and this will primarily act as a failsafe once that is in place, or for folks who would prefer to be prompted.

**Comment by spkane** [comment]
> @spkane can the cludo binary figure out if it has a TTY accessible to it at execution time?

It doesn't have any logic for that yet, but I can add that. The idea of the `interactive` argument was really around being able to say that I don't want to be prompted, even if there is a TTY, for things like shell scripts.

**Comment by spkane** [comment]
@jmcshane Terminal detection has been added.

**Review by jmcshane — APPROVED** [review]
LGTM

**Pull request merged**
