### PR TITLE
Use pre-build hub-tool binary (from our fork)

### PR DESCRIPTION
**Pull request by spkane**
This pulls the patches out of here and relies on a centralized fork of Docker's hub-tool

### CODE REVIEW

**Comment by spkane** [comment]
test PR closure

**Comment by spkane** [comment]
This pulls the patches out of here and relies on a centralized fork of Docker's `hub-tool`

**Comment by spkane** [comment]
closes https://github.com/superorbital/cludo/issues/67

**Comment by tammersaleh** [comment]
lgtm!

**Pull request merged**
